language: python

dist: bionic

python:
  - 3.6

sudo: required

before_install:
  - sudo pip install -U pip && sudo pip install -U setuptools wheel twine
  - npm install -g yarn
  - node --version && npm --version && yarn --version

script:
  - yarn install --cwd ./qpod/base/static/
  - rm -rf ./qpod/base/static/node_modules ./qpod/base/static/yarn.lock ./qpod/base/static/.yarnrc
  - python setup.py sdist bdist_wheel
  - ls -alh ./dist
  - if [ "$TRAVIS_REPO_SLUG" = "QPod/qpod-hub" ] && [ "$TRAVIS_BRANCH" = "release" ]; then
      twine upload dist/* ;  # TWINE_USERNAME/TWINE_PASSWORD need to be set
    fi
