language: python

dist: bionic

python:
  - 3.6

sudo: required

before_install:
  - sudo pip install -U pip && sudo pip install -U setuptools wheel twine
  - npm install -g yarn
  - node --version && npm --version && yarn --version

script:  # TWINE_USERNAME/TWINE_PASSWORD need to be set in CI
  - yarn install --cwd ./qpod/base/static/
  - rm -rf ./qpod/base/static/node_modules ./qpod/base/static/yarn.lock ./qpod/base/static/.yarnrc
  - python -c "import fcntl; fcntl.fcntl(1, fcntl.F_SETFL, 0)"
  - python setup.py sdist bdist_wheel
  - ls -alh ./dist
  - if [ "$TRAVIS_REPO_SLUG" = "QPod/qpod-hub" ] && [ "$TRAVIS_BRANCH" = "release" ]; then
      twine upload dist/* --verbose -u "$TWINE_USERNAME" -p "$TWINE_PASSWORD" ;
    elif [ ! -z "$TWINE_USERNAME" ]; then
      twine upload dist/* --verbose -u "$TWINE_USERNAME" -p "$TWINE_PASSWORD" --repository-url "https://test.pypi.org/legacy/" ;
    fi

notifications:
  slack: q-pod:lrzKf5Ff1Ao1MGclzElR23j4
