language: python

dist: bionic

python:
  - 3.6

sudo: required

before_install:
  - pip install -U pip && pip install -U setuptools wheel twine
  - python -c "import fcntl; fcntl.fcntl(1, fcntl.F_SETFL, 0)"
  - npm install -g npm yarn
  - node --version
  - npm --version
  - yarn --version


script:
  - yarn install --cwd ./qpod/base/static/
  - ls -alh ./qpod/base/static/ && du -h ./qpod/base/static/
  - rm -rf ./qpod/base/static/node_modules ./qpod/base/static/yarn.lock ./qpod/base/static/.yarnrc

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user:
    secure: "YvWg2GUe8dABrqV6jvjgkB/q/67U/8f+6qjQhIgqQysaO/CtmmWmcRlWEHcA65divlz8nmWgAsd0gBVd6ByFyJuCNAwe7n2qu5nQaNBBNQLfb2W/c+C1lsIWA3Fvyzw/6OUv2gshVjktDE9nd4y68SafF5mEGsUMPatI2bqd2kklRLxFtx81kq+maCdzXblZ0XREDPHt4QpmlqZGNr/jURf878zv6Dt9LINkkQY/f04D99rdoNjs8EwpbmwVFtCT2ij2wFq9IhBvlGmUlw1N4RXoJUmV5atVWxi/PPRTQ2Ul5dvtQsqDLVjI6L4iyc66S1e4aXR+kknUul7qjmly23dWKTFvGEKtalD0uzTiyF+AOuTs1hqE24UXpkv6nafmhzvVfc64k644qhXGQ3+3gOoxSl9cQUhxXrN4rNTAOYtXqvRhAl9NtX8FlH+qScc87te3oC5xoXrPPSowag76WgYrJ+k8BoDWssMJ6YwX9fLEqdXfK8NRMh3ChS3C23i3aW8Hewcd/jlnAeDbiGLAIyvHauVy7jj9a4StDNTMb++Vn7gP2svv1TvHXUcetkjyNRNyctJ9x3BM/TUHCCv0g+BBIQlpeTVItG1cnBZ2mK1yZ//lBJ5THT7qXZTkgdCsE2w2crEkgjSLd6fl5WTJO1+socr+WkQpq/d5U3Vs/1w="
  password:
     secure: "ZV8JXJDZiZmeaeMtm+ek/1GOPUZIQtNA6L4oYJO/zw2sjm1QHEOTirm3tpp1Owk2qCqNO0GAIWuq39LUrw49FoPgV7wCLNoZsaGu2g6oX/aoP9cHJ6u3kh3iIaqBSD0RgZIvBMYCNgF2ctrWjOPr6fCMQqycPnY0hNJBxSJTORocPStXF6bFHCmhSmcYfvSRlAiFZTYRN7UHmAzaeGEr4NtaK/6Hg0pJjsicq3jlrlZlEBUMPXl+EVZG//RFKEPd/7a39ARs8beoo99REIcltfSCqsnjaYOIL22GP+4wOrACRBJzW3nR37Rq9qThtFS3P9Eth8omP4SpHERzNLczJegOpjXYco71L4Z+5NQXV1S4OG4ADpJGv+cA+C8xTAiD2/eZTN5LenrSY5AYEoh73xYuyqpDiAGZculEXDN2l3fxgpg2jiUFfrn+0U/4v48GnP1ZaAzvLDqEZ++wGlzDYl1RzrNSxfbaOWYLjr09DLr3bEm6QRtSg2M9ie+hG+SrLydi3z+xXItx1orso7Ad2E1hd8rrlOQa36EhMycFMar19rmVO10VzibUiYeE1QrYNimorQH8B8v525G41/kkUcQv99nUuFiDoUSEQnG5O47TZdEfGvPvKz8P4/22gilYWPkgzlLMflw1pvqXwVDSKjG0CPsbNIjDwODcwbsAR8U="
  on:
    repo: QPod/qpod-hub
    branch: release
